### ISSUE TITLE
Responsive - Blackberry - when the website loads, the menu is fully expanded and you cannot close it. Please see screenshot

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health-Foundation#23]
![img_20161019_093353](https://cloud.githubusercontent.com/assets/8631079/19566058/fcd698d6-96b6-11e6-88a4-381eb64826d9.png)

**Comment by ccmorris** [comment]
This screenshot is actually very helpful. Thank you for that
