### ISSUE TITLE
Homepage - Events - Added image for new event, image gets cut off.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health-Foundation#7]

**Comment by ianfader** [comment]
![screen shot 2016-09-26 at 4 50 16 pm](https://cloud.githubusercontent.com/assets/8989188/18851331/6f5badda-8409-11e6-9a29-46c71b7ead08.png)

**Comment by tgascoigne14** [comment]
![screen shot 2016-09-28 at 8 47 25 am](https://cloud.githubusercontent.com/assets/8631079/18913845/378c2b78-8558-11e6-94b7-f79ac19147bb.png)

This is also happening for news - if the images are not the correct dimensions, please make the image fit the thumbnail.
