### ISSUE TITLE
Events - Calendar - Long titles are being cut off 

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Bluewater-Health-Foundation#9]

**Comment by ccmorris** [comment]
... and what do you want me to do?

**Comment by tgascoigne14** [comment]
If the event title is being cut off, the cut off text should fall onto a second line

**Comment by ccmorris** [comment]
and a third line? and a fourth?

**Comment by tgascoigne14** [comment]
If need be.. the titles won't be that long but the text shouldn't be cut off
